name: Python Deployment Action

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout actions
      - name: Setup Actions
      - uses: actions/checkout@v4

      - name: Setup Python
      - uses: actions/python@v4

      - name: Run python deployment script
        env:
          HOST: ${{secrets.HOST}}
        run: python .github/workflows/server_conn_test.py
