name: Python Deployment Action

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout and Setup actions
      - uses: actions/checkout@v4

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install Dependencies
      - run: |
          python -m pip install requests
          python -m pip install --upgrade pip
          pip install paramiko --ignore-installed

      # Run python deployment script
      -  env:
          HOST: ${{ secrets.RLOM_REMOTE_HOST }}
          USERNAME: ${{ secrets.RLOM_USER_NAME }}
          PASSWORD: ${{ secrets.RLOM_PASSWORD }}
          PASSPHRASE: ${{ secrets.RLOM_PASSPHRASE }}
          PRIVATEKEY: ${{ secrets.RLOM_REMOTE_PK }}
          REMOTEPATH: ${{ secrets.RLOM_REMOTE_PATH }}
          JOBTOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # run: python server_conn.py
      - run: python .github/workflows/server_conn_test.py

              
